Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2021-09, with the labels that each got.

#121 Fix modifying application command by generic ModifyAsync
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Interactions/IApplicationCommand.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Entities/Interactions/RestApplicationCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/RestGlobalCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/RestGuildCommand.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketApplicationCommand.cs
Labels: bug, Internal

#120 Fix validation of arguments for modifying guild permissions of application commands
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
Labels: bug, Internal

#139 Changed the copyright year from 2019 to 2021
  LICENSE
Labels: documentation

#137 Property name: auto_archive_duration
  src/Discord.Net.Rest/API/Rest/StartThreadParams.cs
Labels: Internal

#142 I have changed all the requirements to 1 as they should be according to discords docs
  src/Discord.Net.Core/Entities/Interactions/SlashCommandBuilder.cs
Labels: bug, Internal

#136 Cache unknown thread channel on THREAD_UPDATE
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: bug, Internal

#138 Created 08-bulk-overwrite-of-global-slash-commands.md
  docs/guides/interactions/application-commands/slash-commands/08-bulk-overwrite-of-global-slash-commands.md
Labels: documentation

#145 I've added a link to Bulk overwrite of global slash commands for when it gets commited
  docs/guides/interactions/application-commands/slash-commands/README.md
Labels: documentation

#149 Agument error corrections
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOptionChoice.cs
  src/Discord.Net.Core/Entities/Interactions/SlashCommandBuilder.cs
Labels: enhancement, Internal

#160 Add note about global commands taking up to an hour to apply to docs
  docs/guides/interactions/application-commands/slash-commands/02-creating-slash-commands.md
Labels: documentation

#161 Fixed minor typo in GatewayIntents summary
  src/Discord.Net.Core/GatewayIntents.cs
Labels: documentation

#163 Added warning for Select Menu duplicates values
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
Labels: Internal

#176 Null or empty fix
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Extensions/MessageExtensions.cs
Labels: bug, Internal

#175 Added SendMessagesInThreads and StartEmbeddedActivities.
  src/Discord.Net.Core/Entities/Permissions/GuildPermission.cs
  src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
Labels: enhancement, Internal

#181 Embeds array for send message async
  src/Discord.Net.Commands/Discord.Net.Commands.xml
  src/Discord.Net.Commands/ModuleBase.cs
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs
  src/Discord.Net.Core/Extensions/MessageExtensions.cs
  src/Discord.Net.Core/Extensions/UserExtensions.cs
  src/Discord.Net.Rest/API/Rest/CreateMessageParams.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Channels/IRestMessageChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestDMChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGroupChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Channels/ISocketMessageChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketDMChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedDMChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedGroupChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedTextChannel.cs
Labels: Enhancement, Internal

#183 Fix thread permissions
  src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
  test/Discord.Net.Tests.Unit/GuildPermissionsTests.cs
Labels: Bug, Internal

#186 Use compound assignment
  samples/02_commands_framework/Modules/PublicModule.cs
  src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs
  src/Discord.Net.Commands/Builders/ParameterBuilder.cs
  src/Discord.Net.Commands/CommandService.cs
  src/Discord.Net.Commands/Info/CommandInfo.cs
  src/Discord.Net.Commands/Info/ParameterInfo.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  test/Discord.Net.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs
Labels: Enhancement, Internal

#185 Inlined variable declarations
  src/Discord.Net.Commands/Extensions/MessageExtensions.cs
  src/Discord.Net.Webhook/DiscordWebhookClient.cs
  test/Discord.Net.Tests.Unit/MentionUtilsTests.cs
Labels: Enhancement, Internal

#184 Fixed some warnings
  src/Discord.Net.Commands/Discord.Net.Commands.xml
  src/Discord.Net.Commands/ModuleBase.cs
  src/Discord.Net.Core/CDN.cs
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs
  src/Discord.Net.Core/Entities/Channels/INestedChannel.cs
  src/Discord.Net.Core/Entities/Channels/IStageChannel.cs
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Entities/Interactions/Slash Commands/SlashCommandBuilder.cs
  src/Discord.Net.Core/Entities/Users/IGuildUser.cs
  src/Discord.Net.Core/Extensions/MessageExtensions.cs
  src/Discord.Net.Core/Extensions/UserExtensions.cs
  src/Discord.Net.Core/Net/ApplicationCommandException.cs
  src/Discord.Net.Core/Utils/UrlValidation.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/Entities/Channels/IRestMessageChannel.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.WebSocket/API/Gateway/ExtendedGuild.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Channels/ISocketMessageChannel.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
  test/Discord.Net.Analyzers.Tests/Helpers/CodeFixVerifier.Helper.cs
  test/Discord.Net.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs
  test/Discord.Net.Analyzers.Tests/Verifiers/CodeFixVerifier.cs
  test/Discord.Net.Analyzers.Tests/Verifiers/DiagnosticVerifier.cs
Labels: Documentation, Enhancement, Internal

#189 Object initialization can be simplified fixed
  src/Discord.Net.Core/Entities/Interactions/Slash Commands/SlashCommandBuilder.cs
  test/Discord.Net.Tests.Unit/EmbedBuilderTests.cs
Labels: Enhancement, Internal

#192 Capitalization fixes
  samples/idn/Inspector.cs
  samples/idn/Program.cs
  src/Discord.Net.WebSocket/API/Gateway/InviteCreatedEvent.cs
  test/Discord.Net.Tests.Unit/EmbedBuilderTests.cs
Labels: Enhancement, Internal

#187 Use 'switch' expression
  src/Discord.Net.Core/CDN.cs
  src/Discord.Net.Core/Entities/Interactions/AutocompleteResult.cs
  src/Discord.Net.Core/Entities/Permissions/ChannelPermissions.cs
  src/Discord.Net.Rest/API/Common/ActionRowComponent.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Channels/RestChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGuildChannel.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Net/Converters/EmbedTypeConverter.cs
  src/Discord.Net.Rest/Net/Converters/UserStatusConverter.cs
  src/Discord.Net.Rest/Net/DefaultRestClient.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketChannelHelper.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGuildChannel.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
  src/Discord.Net.WebSocket/Entities/Invites/SocketInvite.cs
Labels: Enhancement, Internal

#196 Add support for sending files with multiple embeds
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs
  src/Discord.Net.Core/Extensions/UserExtensions.cs
  src/Discord.Net.Rest/API/Rest/UploadFileParams.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Channels/IRestMessageChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestDMChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGroupChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Channels/ISocketMessageChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketDMChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedDMChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedGroupChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedTextChannel.cs
Labels: Enhancement, Internal
