Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2021-12, with the labels that each got.

#330 Update GUILD_SCHEDULED_EVENT_CREATE
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: Bug, Internal

#339 Add uppercase character check to SlashCommandBuilder and ApplicationC…
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
Labels: Enhancement

#341 Make IModuleBase and IInteractionModuleBase public
  src/Discord.Net.Commands/IModuleBase.cs
  src/Discord.Net.Interactions/IInteractionModuleBase.cs
Labels: Enhancement, Interaction Service

#342 Fix Autocomplete Command Traversal
  src/Discord.Net.Interactions/Extensions/WebSocketExtensions.cs
  src/Discord.Net.Interactions/Info/Commands/AutocompleteCommandInfo.cs
  src/Discord.Net.Interactions/Info/Parameters/SlashCommandParameterInfo.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/Map/CommandMap.cs
  src/Discord.Net.Interactions/Map/CommandMapNode.cs
Labels: Bug, Interaction Service

#340 Refactor Interactions
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/IMessageCommandInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/IUserCommandInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/IApplicationCommandInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/SlashCommands/ISlashCommandInteraction.cs
  src/Discord.Net.Core/Net/ApplicationCommandException.cs
  src/Discord.Net.Interactions/InteractionModuleBase.cs
  src/Discord.Net.Interactions/RestInteractionModuleBase.cs
  src/Discord.Net.Rest/API/Rest/UploadWebhookFileParams.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestCommandBase.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/MessageCommands/RestMessageCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/UserCommands/RestUserCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Entities/Interactions/MessageComponents/RestMessageComponent.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/RestPingInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestAutocompleteInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestSlashCommand.cs
  src/Discord.Net.Rest/Entities/Messages/RestFollowupMessage.cs
  src/Discord.Net.Rest/Entities/Messages/RestInteractionMessage.cs
  src/Discord.Net.Rest/Extensions/EntityExtensions.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/MessageCommands/SocketMessageCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/UserCommands/SocketUserCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketSlashCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
  src/Discord.Net.WebSocket/Entities/Stickers/SocketSticker.cs
Labels: Enhancement, Discord .NET v3

#343 Fix Module Preconditions
  src/Discord.Net.Interactions/Info/ModuleInfo.cs
Labels: Bug, Interaction Service

#346 Trim SlashCommandInfo.ToString() to remove unncecessary spaces
  src/Discord.Net.Interactions/Info/Commands/CommandInfo.cs
Labels: Enhancement, Interaction Service

#349 Ensure User Left Event
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: Enhancement

#353 Remove DeleteUnknownSlashCommandAck from Interaction Service
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/InteractionServiceConfig.cs
Labels: Enhancement, Interaction Service

#357 Update DiscordRestApiClient.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
Labels: Bug

#360 Introduce emoji role property into rolehelper
  src/Discord.Net.Core/Entities/Roles/RoleProperties.cs
  src/Discord.Net.Rest/API/Rest/ModifyGuildRoleParams.cs
  src/Discord.Net.Rest/Entities/Roles/RoleHelper.cs
Labels: Enhancement

#363 Component to components
  src/Discord.Net.Commands/ModuleBase.cs
  src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs
  src/Discord.Net.Core/Extensions/UserExtensions.cs
  src/Discord.Net.Interactions/InteractionModuleBase.cs
  src/Discord.Net.Interactions/RestInteractionModuleBase.cs
  src/Discord.Net.Interactions/Utilities/InteractionUtility.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Channels/IRestMessageChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestDMChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGroupChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestCommandBase.cs
  src/Discord.Net.Rest/Entities/Interactions/MessageComponents/RestMessageComponent.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/RestPingInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Channels/ISocketMessageChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketDMChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.Webhook/DiscordWebhookClient.cs
  src/Discord.Net.Webhook/WebhookClientHelper.cs
Labels: Discord .NET v3

#367 Fix coin emoji missing
  src/Discord.Net.Core/Entities/Emotes/Emoji.cs
Labels: Internal

#362 feature: interaction response with files
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Core/Entities/Messages/FileAttachment.cs
  src/Discord.Net.Rest/API/Rest/UploadInteractionFileParams.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.Rest/Entities/Messages/RestInteractionMessage.cs
  src/Discord.Net.Rest/Extensions/EntityExtensions.cs
  src/Discord.Net.Rest/Net/DefaultRestClient.cs
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
  src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: Enhancement, Discord .NET v3

#370 Built-in Interaction Service Preconditions
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireBotPermissionAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireContextAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireNsfwAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireOwnerAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireRoleAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireUserPermissionAttribute.cs
Labels: Enhancement, Interaction Service

#373 Add guild parameter to UserLeftEvent
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: Enhancement

#381 Fix v2-v3 format issue
  docs/guides/v2_v3_guide/v2_to_v3_guide.md
Labels: Documentation, Discord .NET v3

#384 Fix CommandExecuted not invoked on failed parse
  src/Discord.Net.Commands/CommandService.cs
Labels: Bug

#383 Add callback to rest context
  src/Discord.Net.Core/Interactions/IRestInteractionContext.cs
  src/Discord.Net.Interactions/AutocompleteHandlers/AutocompleteHandler.cs
  src/Discord.Net.Interactions/RestInteractionModuleBase.cs
  src/Discord.Net.Rest/Interactions/RestInteractionContext.cs
Labels: Enhancement, Interaction Service

#382 Fixed applications not containing the TOS and Privacy strings.
  src/Discord.Net.Core/Entities/IApplication.cs
  src/Discord.Net.Rest/API/Common/Application.cs
  src/Discord.Net.Rest/Entities/RestApplication.cs
Labels: Enhancement, Internal

#391 Make module service scopes optional
  src/Discord.Net.Interactions/Info/Commands/CommandInfo.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/InteractionServiceConfig.cs
Labels: Interaction Service

#389 Add before and after execute async to interaction modules
  src/Discord.Net.Interactions/Builders/ModuleClassBuilder.cs
  src/Discord.Net.Interactions/IInteractionModuleBase.cs
  src/Discord.Net.Interactions/InteractionModuleBase.cs
Labels: Enhancement

#388 Feature/guilduser timeouts
  src/Discord.Net.Core/Entities/Users/GuildUserProperties.cs
  src/Discord.Net.Core/Entities/Users/IGuildUser.cs
  src/Discord.Net.Rest/API/Common/GuildMember.cs
  src/Discord.Net.Rest/API/Rest/ModifyGuildMemberParams.cs
  src/Discord.Net.Rest/Entities/Users/RestGuildUser.cs
  src/Discord.Net.Rest/Entities/Users/RestWebhookUser.cs
  src/Discord.Net.Rest/Entities/Users/UserHelper.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGuildUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketWebhookUser.cs
Labels: Enhancement, Fresh feature

#371 Interaction Service Complex Parameters
  src/Discord.Net.Interactions/Attributes/ComplexParameterAttribute.cs
  src/Discord.Net.Interactions/Attributes/ComplexParameterCtorAttribute.cs
  src/Discord.Net.Interactions/Builders/ModuleClassBuilder.cs
  src/Discord.Net.Interactions/Builders/Parameters/SlashCommandParameterBuilder.cs
  src/Discord.Net.Interactions/Info/Commands/CommandInfo.cs
  src/Discord.Net.Interactions/Info/Commands/SlashCommandInfo.cs
  src/Discord.Net.Interactions/Info/Parameters/SlashCommandParameterInfo.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/Results/ParseResult.cs
  src/Discord.Net.Interactions/Utilities/ApplicationCommandRestUtil.cs
  src/Discord.Net.Interactions/Utilities/ReflectionUtils.cs
Labels: Enhancement, Internal, Interaction Service

#399 Add MaxUploadLimit to guilds
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: Enhancement

#403 Add RTCRegion to audio channels
  src/Discord.Net.Core/Entities/Channels/IAudioChannel.cs
  src/Discord.Net.Rest/API/Common/Channel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGroupChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestVoiceChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketVoiceChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedGroupChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedVoiceChannel.cs
Labels: Enhancement

#407 Display name support for enum type converter
  docs/guides/int_framework/samples/intro/groupattribute.cs
  samples/04_interactions_framework/ExampleEnum.cs
  src/Discord.Net.Interactions/Attributes/EnumChoiceAttribute.cs
  src/Discord.Net.Interactions/TypeConverters/EnumConverter.cs
Labels: Enhancement, Internal, Interaction Service
