Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2021-10, with the labels that each got.

#205 Add competing activity status type
  src/Discord.Net.Core/Entities/Activities/ActivityType.cs
Labels: Enhancement, Internal

#204 Add Icons to IRole
  src/Discord.Net.Core/CDN.cs
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Roles/IRole.cs
  src/Discord.Net.Rest/API/Common/Role.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/Entities/Roles/RestRole.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Roles/SocketRole.cs
Labels: Enhancement, Internal

#174 Added Clean Content Function
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Format.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Messages/SocketMessage.cs
  test/Discord.Net.Tests.Unit/FormatTests.cs
Labels: Enhancement, Internal

#212 Clean Content Expanded
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Messages/IMessage.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs
  src/Discord.Net.Rest/Entities/Messages/RestMessage.cs
  src/Discord.Net.WebSocket/Entities/Messages/SocketMessage.cs
Labels: Enhancement

#215 Spelling corrections
  samples/02_commands_framework/Program.cs
  samples/03_sharded_client/Services/CommandHandlingService.cs
  src/Discord.Net.Commands/Attributes/AliasAttribute.cs
  src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs
  src/Discord.Net.Commands/CommandService.cs
  src/Discord.Net.Commands/ModuleBase.cs
  src/Discord.Net.Commands/RunMode.cs
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Interactions/Context Menus/MessageCommandBuilder.cs
  src/Discord.Net.Core/Entities/Interactions/Context Menus/UserCommandBuilder.cs
  src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteractionData.cs
  src/Discord.Net.Core/Entities/Interactions/InteractionResponseType.cs
  src/Discord.Net.Core/Entities/Interactions/Slash Commands/SlashCommandBuilder.cs
  src/Discord.Net.Core/Entities/Interactions/Slash Commands/SlashCommandProperties.cs
  src/Discord.Net.Core/Entities/Messages/IMessage.cs
  src/Discord.Net.Core/Entities/Messages/TimestampTag.cs
  src/Discord.Net.Core/Entities/Permissions/ChannelPermissions.cs
  src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
  src/Discord.Net.Core/Entities/Permissions/OverwritePermissions.cs
  src/Discord.Net.Core/Entities/Stickers/ICustomSticker.cs
  src/Discord.Net.Core/Extensions/MessageExtensions.cs
  src/Discord.Net.Core/Format.cs
  src/Discord.Net.Core/RequestOptions.cs
  src/Discord.Net.Examples/Core/Entities/Channels/IMessageChannel.Examples.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Channels/RestThreadChannel.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Entities/Messages/CustomSticker.cs
  src/Discord.Net.Rest/Entities/Messages/RestFollowupMessage.cs
  src/Discord.Net.Rest/Entities/Messages/RestInteractionMessage.cs
  src/Discord.Net.Rest/Entities/Webhooks/WebhookHelper.cs
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
  src/Discord.Net.WebSocket/API/Voice/ReadyEvent.cs
  src/Discord.Net.WebSocket/Audio/Streams/BufferedWriteStream.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/DiscordSocketConfig.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketStageChannel.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Context Menu Commands/Message Commands/SocketMessageCommandData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketAutocompleteInteractionData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketSlashCommandDataOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
  src/Discord.Net.WebSocket/Entities/Stickers/SocketCustomSticker.cs
  test/Discord.Net.Tests.Unit/EmbedBuilderTests.cs
  test/Discord.Net.Tests.Unit/FormatTests.cs
Labels: Documentation, Enhancement

#216 Followup with file async warnings
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: Enhancement

#217 Add channel types in application command options.
  src/Discord.Net.Commands/Discord.Net.Commands.xml
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/Slash Commands/SlashCommandBuilder.cs
  src/Discord.Net.Rest/API/Common/ApplicationCommandOption.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/Entities/Interactions/RestApplicationCommandOption.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketApplicationCommandOption.cs
Labels: Enhancement

#218 Remove file extension check
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
Labels: Internal

#267 Add missing values to SystemChannelMessageDeny
  src/Discord.Net.Core/Entities/Guilds/GuildProperties.cs
  src/Discord.Net.Core/Entities/Guilds/SystemChannelMessageDeny.cs
  src/Discord.Net.Core/Extensions/GuildExtensions.cs
Labels: Enhancement, Hacktoberfest-accepted
