Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2021-11, with the labels that each got.

#269 Amend creating slash command guide
  docs/guides/interactions/application-commands/slash-commands/02-creating-slash-commands.md
Labels: Documentation

#273 Support Min and Max values on ApplicationCommandOptions
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
  src/Discord.Net.Core/Entities/Interactions/Slash Commands/SlashCommandBuilder.cs
  src/Discord.Net.Rest/API/Common/ApplicationCommandOption.cs
  src/Discord.Net.Rest/Entities/Interactions/RestApplicationCommandOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketApplicationCommandOption.cs
Labels: Enhancement

#276 Automatically fix ordering of optional command options
  src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
Labels: Enhancement

#282 Fix maximum number of Select Menu Options
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentBuilder.cs
Labels: Enhancement

#283 Interaction Specific Interfaces
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/IMessageCommandInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/IMessageCommandInteractionData.cs
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/IUserCommandInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/IUserCommandInteractionData.cs
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/IComponentInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/IComponentInteractionData.cs
  src/Discord.Net.Core/Entities/Interactions/SlashCommands/IAutocompleteInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/SlashCommands/IAutocompleteInteractionData.cs
  src/Discord.Net.Core/Entities/Interactions/SlashCommands/ISlashCommandInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/MessageCommands/RestMessageCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/MessageCommands/RestMessageCommandData.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/UserCommands/RestUserCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/UserCommands/RestUserCommandData.cs
  src/Discord.Net.Rest/Entities/Interactions/MessageComponents/RestMessageComponent.cs
  src/Discord.Net.Rest/Entities/Interactions/MessageComponents/RestMessageComponentData.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestAutocompleteInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestAutocompleteInteractionData.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestSlashCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/MessageCommands/SocketMessageCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/MessageCommands/SocketMessageCommandData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/UserCommands/SocketUserCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/UserCommands/SocketUserCommandData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponentData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteractionData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketSlashCommand.cs
Labels: Enhancement

#279 Add Guild Scheduled Events
  docs/guides/guild_events/creating-guild-events.md
  docs/guides/guild_events/getting-event-users.md
  docs/guides/guild_events/intro.md
  docs/guides/guild_events/modifying-events.md
  docs/guides/toc.yml
  src/Discord.Net.Core/DiscordConfig.cs
  src/Discord.Net.Core/Entities/Guilds/GuildScheduledEventPrivacyLevel.cs
  src/Discord.Net.Core/Entities/Guilds/GuildScheduledEventStatus.cs
  src/Discord.Net.Core/Entities/Guilds/GuildScheduledEventType.cs
  src/Discord.Net.Core/Entities/Guilds/GuildScheduledEventsProperties.cs
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Guilds/IGuildScheduledEvent.cs
  src/Discord.Net.Core/Entities/Permissions/GuildPermission.cs
  src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
  src/Discord.Net.Core/GatewayIntents.cs
  src/Discord.Net.Rest/API/Common/GuildScheduledEvent.cs
  src/Discord.Net.Rest/API/Common/GuildScheduledEventEntityMetadata.cs
  src/Discord.Net.Rest/API/Common/GuildScheduledEventUser.cs
  src/Discord.Net.Rest/API/Rest/CreateGuildScheduledEventParams.cs
  src/Discord.Net.Rest/API/Rest/GetEventUsersParams.cs
  src/Discord.Net.Rest/API/Rest/ModifyGuildScheduledEventParams.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuildEvent.cs
  src/Discord.Net.Rest/Entities/Users/RestUser.cs
  src/Discord.Net.Rest/Net/Converters/UnixTimestampConverter.cs
  src/Discord.Net.WebSocket/API/Gateway/ExtendedGuild.cs
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuildEvent.cs
  test/Discord.Net.Tests.Unit/GuildPermissionsTests.cs
Labels: Enhancement, Waiting for feature (Discord)

#292 Make RestUserCommand public
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/UserCommands/RestUserCommand.cs
Labels: Bug

#284 Change the minimum length of slash commands to 1
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/MessageCommandBuilder.cs
  src/Discord.Net.Core/Entities/Interactions/ContextMenus/UserCommandBuilder.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
Labels: Bug, Enhancement

#297 Fix ratelimit timings
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
  src/Discord.Net.Rest/Net/RateLimitInfo.cs
Labels: Bug, TODO, Internal

#301 Add Audit Log Data classes for Threads
  src/Discord.Net.Rest/Entities/AuditLogs/AuditLogHelper.cs
  src/Discord.Net.Rest/Entities/AuditLogs/DataTypes/ThreadCreateAuditLogData.cs
  src/Discord.Net.Rest/Entities/AuditLogs/DataTypes/ThreadDeleteAuditLogData.cs
  src/Discord.Net.Rest/Entities/AuditLogs/DataTypes/ThreadInfo.cs
  src/Discord.Net.Rest/Entities/AuditLogs/DataTypes/ThreadUpdateAuditLogData.cs
Labels: Enhancement

#308 Fix SocketVoiceChannel options are created as generic mentionables in Interaction service
  docs/guides/interactions_framework/typeconverters.md
  src/Discord.Net.Interactions/InteractionService.cs
Labels: Internal, Interaction Service

#311 Improve the `GuildFeatures` converter
  src/Discord.Net.Rest/Net/Converters/GuildFeaturesConverter.cs
Labels: Enhancement

#322 Fix NRE on service providerless command execution
  src/Discord.Net.Interactions/Info/Commands/CommandInfo.cs
Labels: Bug, Interaction Service

#326 Fix Wrong link in interactions framework docs
  docs/guides/interactions_framework/intro.md
Labels: Documentation

#328 Make autocomplete log virtual
  src/Discord.Net.Interactions/AutocompleteHandlers/AutocompleteHandler.cs
Labels: Enhancement, Interaction Service
