Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2021-07, with the labels that each got.

#37 Update README section about InteractivityAddon
  README.md
Labels: documentation

#39 Add slash command delete operations
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: enhancement

#27 Implemented new instant invite types
  src/Discord.Net.Core/Entities/Channels/INestedChannel.cs
  src/Discord.Net.Core/Entities/Invites/TargetUserType.cs
  src/Discord.Net.Rest/API/Rest/CreateChannelInviteParams.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestVoiceChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketVoiceChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedTextChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedVoiceChannel.cs
Labels: enhancement

#48 Fix error message typo when creating slash commands
  src/Discord.Net.Core/Entities/Interactions/SlashCommandBuilder.cs
Labels: Internal

#47 Add note about slash command creation
  docs/guides/slash-commands/02-creating-slash-commands.md
Labels: documentation

#46 Minor doc fix
  docs/guides/slash-commands/04-parameters.md
Labels: documentation

#44 Add IsSpecified check to Author field
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
Labels: Internal

#49 Changes on Emote/Emoji and SelectMenu
  README.md
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Emotes/Emoji.cs
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Entities/Interactions/Message Components/SelectMenu.cs
  src/Discord.Net.Rest/API/Common/SelectMenuComponent.cs
  src/Discord.Net.Rest/Entities/Messages/RestMessage.cs
  src/Discord.Net.WebSocket/Entities/Messages/SocketMessage.cs
Labels: Internal

#51 Update limits per Discord API docs (https://discord.com/developers/do…
  src/Discord.Net.Core/Entities/Interactions/SlashCommandBuilder.cs
Labels: Internal

#50 Improvements builders docs and adding/renaming methods/constructors and some fixes
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
Labels: Internal, documentation

#57 Remove necessary things and some fix/changes
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Utils/Optional.cs
  src/Discord.Net.Rest/API/Common/InteractionCallbackData.cs
  src/Discord.Net.Rest/API/Common/InteractionResponse.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketSlashCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: Internal

#58 Refactor interaction methods and some changes
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Entities/Messages/MessageProperties.cs
  src/Discord.Net.Rest/API/Common/InteractionCallbackData.cs
  src/Discord.Net.Rest/API/Rest/CreateWebhookMessageParams.cs
  src/Discord.Net.Rest/API/Rest/ModifyMessageParams.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs
  src/Discord.Net.Rest/Entities/Messages/RestInteractionMessage.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketSlashCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
  src/Discord.Net.Webhook/WebhookClientHelper.cs
Labels: Internal, enhancement

#60 Add new `NUMBER` option type (https://discord.com/developers/docs/int…
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOptionType.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketSlashCommandDataOption.cs
Labels: Internal, enhancement

#66 Fixed url validation to be neater and not utilize IsWellFormatted
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
  src/Discord.Net.Core/Utils/UrlValidation.cs
Labels: Internal, enhancement

#70 Add missing message types (Needs descriptions)
  src/Discord.Net.Core/Entities/Messages/MessageType.cs
Labels: Internal, enhancement, help wanted

#72 Restoring the option to send a single embed in interaction responses.
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Slash Commands/SocketSlashCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: Internal
