Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2021-08, with the labels that each got.

#80 Add `NsfwLevel` property to Guild
  src/Discord.Net.Core/Discord.Net.Core.xml
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Guilds/NsfwLevel.cs
  src/Discord.Net.Rest/API/Common/Guild.cs
  src/Discord.Net.Rest/Discord.Net.Rest.xml
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: Internal, enhancement

#79 Docs update
  README.md
  docs/guides/emoji/emoji.md
  docs/guides/slash-commands/03-responding-to-slash-commands.md
Labels: documentation

#76 Fix Emoji UnicodeAndNames throwing exception because of duplicit keys
  src/Discord.Net.Core/Entities/Emotes/Emoji.cs
Labels: Internal

#91 Update label/description lengths for selects (ref: https://github.com…
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
Labels: Internal

#90 Fix tests
  test/Discord.Net.Tests.Unit/GuildPermissionsTests.cs
Labels: bug, Internal

#96 Gateway serialization was recently changed to not send null values
  src/Discord.Net.Rest/DiscordRestApiClient.cs
Labels: bug, Internal

#93 Add missing guild permissions
  src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
  test/Discord.Net.Tests.Unit/GuildPermissionsTests.cs
Labels: Internal

#81 Add banner and accent color to user and some fixes/improvements
  src/Discord.Net.Core/CDN.cs
  src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
  src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
  src/Discord.Net.Core/Entities/Roles/Color.cs
  src/Discord.Net.Core/Entities/Users/IUser.cs
  src/Discord.Net.Rest/API/Common/User.cs
  src/Discord.Net.Rest/Entities/Users/RestThreadUser.cs
  src/Discord.Net.Rest/Entities/Users/RestUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGlobalUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGroupUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGuildUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketSelfUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUnknownUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketWebhookUser.cs
  test/Discord.Net.Tests.Unit/GuildPermissionsTests.cs
Labels: enhancement, Internal

#100 Assign CurrentUserId in Sharded Client
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
Labels: bug, Internal

#105 Sharded Client Application Command Events and CurrentUserId Issue
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
Labels: bug, Internal

#128 Fix ephemeral command differs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
Labels: bug, Internal

#132 Fix Guild Owner and Admin GuildPermissions.All
  src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
Labels: bug, Internal

#131 Allow file uploading on followup
  src/Discord.Net.Rest/API/Rest/CreateWebhookMessageParams.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.xml
  src/Discord.Net.WebSocket/Entities/Interaction/Message Components/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: enhancement, Internal
