Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2022-01, with the labels that each got.

#411 Add timeout events
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: Enhancement

#415 User locale in interactions
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Rest/API/Common/Interaction.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: Enhancement, Fresh feature

#417 Docs update
  docs/guides/v2_v3_guide/v2_to_v3_guide.md
  docs/index.md
Labels: Documentation

#422 Add missing guild features
  src/Discord.Net.Core/Entities/Guilds/GuildFeature.cs
  src/Discord.Net.Core/Entities/Guilds/GuildFeatures.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
Labels: Enhancement

#421 Add default ratelimit callback
  src/Discord.Net.Core/DiscordConfig.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.WebSocket/BaseSocketClient.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketApiClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.Webhook/DiscordWebhookClient.cs
Labels: Enhancement

#420 Add AddRow and WithRows
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentBuilder.cs
Labels: Enhancement

#423 Add GetChannelType extension method
  src/Discord.Net.Core/Extensions/ChannelExtensions.cs
Labels: Enhancement

#424 Fix exception when uploading files
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
Labels: Bug

#426 Fix ApplicationId in Interactions.
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.WebSocket/API/Gateway/PartialApplication.cs
  src/Discord.Net.WebSocket/API/Gateway/ReadyEvent.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
Labels: Bug

#429 Enforce valid button styles
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentBuilder.cs
Labels: Bug, Enhancement

#427 Change AddReactionsAsync() and RemoveReactionsAsync() signature
  src/Discord.Net.Core/Extensions/MessageExtensions.cs
Labels: Enhancement
