Repository Discord-Net-Labs/Discord.Net-Labs, pull requests merged in 2022-02, with the labels that each got.

#445 Add support for attachments
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOptionType.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/TypeConverters/DefaultEntityTypeConverter.cs
  src/Discord.Net.Rest/API/Common/ApplicationCommandInteractionDataResolved.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestResolvableData.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestSlashCommandDataOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketSlashCommandDataOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketResolvableData.cs
Labels: Enhancement, Fresh feature

#447 Feature: Allow modifying attachments on interactions and extend the module base
  src/Discord.Net.Interactions/InteractionModuleBase.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
Labels: Enhancement

#448 Fix Current user null on reconnect
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: Bug
